#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
#  typeAliasesPackage: com.hgg.entity
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev

#数据库
  datasource:
    url: jdbc:mysql://localhost:3306/muses
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#静态页面
    thymeleaf:
        prefix: classpath:/templates
        suffix: .html

#端口号
server:
  port: 6060
#  context-path: /com


